version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Test can run here!"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Java & Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y curl git && sudo apt-get install -y openjdk-8-jdk"      
      - run:
          name: Delete Old DataBase
          command: ssh $SSH_USER@$SSH_HOST "rm -f userWord.mv.db && rm -r wordbanksProject"
      - run:
          name: Clone repo
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/georgepemberton1998/wordbanksProject.git"
      - run:
          name: Maven install
          command: ssh $SSH_USER@$SSH_HOST "cd ~/wordbanksProject && sudo apt-get install -y maven"        
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/wordbanksProject && mvn verify"

      - run:
          name: Run application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/wordbanksProject && mvn -Dmaven.test.skip=true spring-boot:run"
          no_output_timeout: 45m
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

